/** @type {import('next').NextConfig} */
const nextConfig = {
  // Repository guidance is maintained explicitly, not generated by next dev.
  agentRules: false,
  async headers() {
    return [
      {
        // Email documents load these public, versioned fonts across origins.
        source: '/fonts/poppins/:file',
        headers: [{ key: 'Access-Control-Allow-Origin', value: '*' }],
      },
      {
        source: '/email-preview/:file',
        headers: [{ key: 'X-Robots-Tag', value: 'noindex, nofollow' }],
      },
    ];
  },
};
module.exports = nextConfig;
